name: Moodle PHPCS Check

on:
  push:
    paths:
      - '**.php'
  pull_request:
    paths:
      - '**.php'

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install Composer globally
        run: sudo apt-get install -y composer

      - name: Install PHP_CodeSniffer
        run: composer global require squizlabs/php_codesniffer

      - name: Install Moodle Coding Standard
        run: |
          git clone https://github.com/moodlehq/moodle-cs.git ~/moodle-cs

      - name: Install PHPCS dependency standards
        run: |
          composer global require dealerdirect/phpcodesniffer-composer-installer
          composer global require phpcompatibility/php-compatibility
          composer global require sirbrillig/phpcs-normalized-arrays
          composer global require object-calisthenics/phpcs-calisthenics-rules

      - name: Configure installed_paths for PHPCS
        run: |
          ~/.composer/vendor/bin/phpcs --config-set installed_paths \
            ~/moodle-cs,\
            ~/.composer/vendor/phpcompatibility/php-compatibility,\
            ~/.composer/vendor/sirbrillig/phpcs-normalized-arrays,\
            ~/.composer/vendor/object-calisthenics/phpcs-calisthenics-rules

      - name: Show available standards
        run: ~/.composer/vendor/bin/phpcs -i

      - name: Run PHPCS
        run: |
          ~/.composer/vendor/bin/phpcs \
            --standard=moodle \
            --extensions=php \
            --ignore=vendor/ \
            .